apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: container
        image: crccheck/hello-world
        ports:
        - containerPort: 80 # Puerto interno del contenedor
---
apiVersion: v1
kind: Service
metadata:
  name: gameservice
spec:
  type: LoadBalancer
  ports:
  - port: 8089        # <--- El puerto que tú usarás en el navegador
    targetPort: 80    # <--- El puerto al que el Service enviará el tráfico (el del contenedor)
  selector:
    app: game
